services:
  db:
    image: mysql
    container_name: docker_mysql
    environment:
      MYSQL_DATABASE: data_migration
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./data:/app/data

  phpMyAdmin:
    image: phpmyadmin
    container_name: docker_phpadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

volumes:
  mysql_data: