services:
  db:
    image: mysql
    container_name: docker_mysql
    environment:
      MYSQL_DATABASE: data_migration
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpMyAdmin:
    image: phpmyadmin
    container_name: docker_phpadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"